version: "3"
services:
  app:
    build: ./app
    command: python app.py
    links:
      - db
      - mqtt
    ports:
      - "5000:5000"

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "iotDB"
      POSTGRES_USER: "userDB"
      POSTGRES_PASSWORD: "passwordDB"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  mqtt: 
    image: eclipse-mosquitto
    container_name: mosquitto 
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
